/*Tabla KIO_CATALOGOPORTAFOLIO*/
DROP TABLE KIO_CATALOGOPORTAFOLIO IF EXISTS;
CREATE TABLE KIO_CATALOGOPORTAFOLIO (
  id         INTEGER PRIMARY KEY,
  nombreProyecto VARCHAR(150),
  responsableProyecto  VARCHAR(50)
);

/*Tabla KIO_CATALOGOREQUERIMIENTOS*/
DROP TABLE KIO_CATALOGOREQUERIMIENTOS IF EXISTS;
CREATE TABLE KIO_CATALOGOREQUERIMIENTOS (
  id         INTEGER PRIMARY KEY,
  nombreRequerimiento VARCHAR(50),
);

/*Tabla KIO_CATALOGOSERVICIOS*/
DROP TABLE KIO_CATALOGOSERVICIOS IF EXISTS;
CREATE TABLE KIO_CATALOGOSERVICIOS (
  idServicio          INTEGER PRIMARY KEY,
  tipoServicio VARCHAR(50),
  descripcionServicio VARCHAR(200),
);

/*Tabla KIO_CATALOGOSERVICIOS*/
DROP TABLE KIO_CATALOGOSERVICIOS IF EXISTS;
CREATE TABLE KIO_CATALOGOSERVICIOS (
  idServicio          INTEGER PRIMARY KEY,
  tipoServicio VARCHAR(50),
  descripcionServicio VARCHAR(200),
);

/*Tabla KIO_CATALOGOBLOQUECONSTRUCCION*/
DROP TABLE KIO_CATALOGOBLOQUECONSTRUCCION IF EXISTS;
CREATE TABLE KIO_CATALOGOBLOQUECONSTRUCCION (
  idBloqueContruccion          INTEGER PRIMARY KEY,
  nombreBloque VARCHAR(200),
  descripcionBloque VARCHAR(200),
);

/*Tabla KIO_CATALOGOBLOQUECONSTRUCCION*/
DROP TABLE KIO_CATALOGOMODALIDAD IF EXISTS;
CREATE TABLE KIO_CATALOGOMODALIDAD (
  idModalidad          INTEGER PRIMARY KEY,
  tipoModalidad VARCHAR(20),
  descripcionModalidad VARCHAR(200),
);

/*Tabla KIO_SERVICIO_MODALIDAD*/
DROP TABLE KIO_SERVICIO_MODALIDAD IF EXISTS;
CREATE TABLE KIO_SERVICIO_MODALIDAD (
  idServicioModalidad INTEGER PRIMARY KEY,
  idServicio INTEGER,
  idModalidad INTEGER,
);

/*Tabla KIO_MODALIDAD_BLOQUE*/
DROP TABLE KIO_MODALIDAD_BLOQUE IF EXISTS;
CREATE TABLE KIO_MODALIDAD_BLOQUE (
  idModalidadBloque INTEGER PRIMARY KEY,
  idBloqueContruccion INTEGER,
  idModalidad INTEGER,
);