INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (1,'Análisis de código Mainframe Z/10 para factibilidad de migración','Gabriel Tlaxcalteco Tecalco');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (2,'Analítica de Comprobación de Supervivencia','Araceli Bonilla Ávila');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (3,'Aplicación Móvil IMSS Digital 3.1','Israel Breton Hernández');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (4,'Aplicación Móvil IMSS Digital V4.0','Israel Breton Hernández');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (5,'Aplicación Móvil IMSS Digital V4.1','Israel Breton Hernández');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (6,'Automatización en el flujo de documentos de la unidad de personal a través de Firma electrónica avanzada.','Roberto Javier Garcia Perez');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (7,'Código Infarto ','Luis Emmanuel Margain Terrazas');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (8,'Consulta de vigencia en 2° y 3° nivel','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (9,'Corrección de Datos de Asegurados con CURP','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (10,'CSI: Integración de la funcionalidad de BS, CMI y Lab','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (11,'ECE Despliegue ','Luis Emmanuel Margain Terrazas');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (12,'Expediente Clínico Electrónico IMSS (ECE IMSS) NOM 024 ','Luis Emmanuel Margain Terrazas');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (13,'Firma Electrónica de manera masiva para los Créditos Fiscales Emitidos por el Aplicativo SIVEPA Y ECOS ','José Luis Herrera Chávez');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (14,'Implementación y Puesta en  marcha de la cadena de suministro del IMSS PeopleSoft V9.1 (Nuevo Modelo de Abasto)','Raúl Borunda Castillo');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (15,'Implementación y puesta en marcha finanzas PeopleSoft versión 9.1 Fase II(FSCM)','Raúl Borunda Castillo');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (16,'Juicio Contencioso Administrativo Federal IMSS Actor Amparos y Recursos','Roberto Javier Garcia Perez');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (17,'Migración PREI 8.8 a KIO','Marlene Silvestre Ocaña ');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (18,'Modelo Intregral de Control de Obligaciones','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (19,'Nuevo Dictamen Electrónico - Pagos y Movimientos Afiliatorios','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (20,'Nuevo Dictamen Electrónico - dictamen','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (21,'Nuevo Dictamen Electrónico - contadores públicos/Presentación de dictamen','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (22,'Nuevo Modelo de Pago de Subsidios','Araceli Bonilla Ávila');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (23,'Publicación de los RTT en Portal del IMSS','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (24,'Registro de Obras de la Construcción','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (25,'Renovaciones IVRO, SSF, CVRO','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (26,'Repositorio Central en Salud','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (27,'Semáforo de Diabetes Melitus y de Hipertensión Arterial para Derechohabientes del IMSS (CHKT)','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (28,'Servicio Digital de Emisión de Facturas','Marlene Silvestre Ocaña ');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (29,'Servicio Digital de Productividad Médica','Israel Breton Hernández');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (30,'Servicio para Optimización de Procesos en Segundo y Tercer nivel  (Gestión de Camas)','Luis Emmanuel Margain Terrazas');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (31,'SIEID para Dictamen','Gabriel Tlaxcalteco Tecalco');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (32,'SIMF: Certificación SIMF NOM024-SSA3-2012','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (33,'SIMF: Reportes ','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (34,'SIMF: Sistema de Información de Medicina Familiar V 4.10','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (35,'Simplificación del proceso de prestaciones de maternidad','Araceli Bonilla Ávila');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (36,'Sistema de Administración de Siniestros ','Marlene Silvestre Ocaña ');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (37,'Sistema de Certificación de Semanas Cotizadas a Salud del Asegurado ','Tomas García Alanis');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (38,'Sistema de Información Médico Operativo-Central','Teresita de Jesús Miranda');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (39,'Sistema de translado de Pacientes (STP)','Roberto Javier Garcia Perez');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (40,'Tesoreria: Conciliación de cuentas banacarias en el instituto','Marlene Silvestre Ocaña ');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (41,'Tesoreria: Fondeo a cuentas pagadoras y de evolución o recursos no ejercidos host to host','Marlene Silvestre Ocaña ');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (42,'Trámite de Solicitud de Pensión por Internet','Araceli Bonilla Ávila');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (43,'Vinculación de la administración Financiera PeopleSoft 9.1','Roberto Javier Garcia Perez');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (44,'Transformación de la Administración Financiera (TAF) ','Roberto Javier Garcia Perez');
INSERT INTO KIO_CATALOGOPORTAFOLIO VALUES (45,'Pase de cirugía','Teresita de Jesús Miranda');