/*OBTIENE LAS MODALIDADES PARA GOBIERNO*/
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (1,1,1);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (2,1,2);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (3,1,3);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (4,1,4);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (5,1,5);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (6,1,10);

/*OBTIENE LAS MODALIDADES PARA SANI*/
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (7,2,6);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (8,2,7);

/*OBTIENE LAS MODALIDADES PARA SCONI*/
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (9,3,1);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (10,3,2);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (11,3,9);

/*OBTIENE LAS MODALIDADES PARA SINI*/
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (12,4,3);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (13,4,5);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (14,4,8);

/*OBTIENE LAS MODALIDADES PARA SSNI*/
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (15,5,1);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (16,5,2);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (17,5,3);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (18,5,4);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (19,5,5);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (20,5,6);
INSERT INTO KIO_SERVICIO_MODALIDAD VALUES (21,5,11);