/*OBTIENE BLOQUE CONSTRUCCION PARA SERVIDOR-RISC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (1,1,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (2,1,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (3,1,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (4,1,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-PROC-RISC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (5,2,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (6,2,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (7,2,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (8,2,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-RISC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (9,3,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (10,3,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (11,3,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (12,3,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVIDOR-X86*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (13,4,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (14,4,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (15,4,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (16,4,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (17,4,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-PROC-X86*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (18,5,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (19,5,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (20,5,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (21,5,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (22,5,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-128GB-X86*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (23,6,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (24,6,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (25,6,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (26,6,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (27,6,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA MODULO-HSM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (28,7,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (29,7,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (30,7,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (31,7,5);


/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-DUP-30TB-MF*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (32,9,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (33,9,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (34,9,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (35,9,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-COMP-MF*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (36,10,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (37,10,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (38,10,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (39,10,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ALMACENAMIENTO-IND*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (40,11,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (41,11,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (42,11,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (43,11,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (44,11,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-100GB-ALM-IND*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (45,12,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (46,12,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (47,12,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (48,12,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (49,12,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA RESPALDO-IND*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (50,13,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (51,13,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (52,13,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (53,13,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (54,13,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UNIDAD-ALM-ARCH-CONT*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (55,14,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (56,14,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (57,14,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (58,14,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (59,14,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-24TB-ALM-ARCH-CONT*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (60,15,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (61,15,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (62,15,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (63,15,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (64,15,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UNIDAD-ALMACENAMIENTO-MEDIA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (65,16,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (66,16,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (67,16,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (68,16,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (69,16,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-DISCO-FC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (70,18,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (71,18,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (72,18,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (73,18,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (74,18,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-DISCO-SATA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (76,19,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (77,19,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (78,19,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (79,19,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (80,19,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UNIDAD-RESPLADOS-PA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (81,20,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (82,20,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (83,20,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (84,20,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (85,20,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-30TB-RAID5-PA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (86,21,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (87,21,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (88,21,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (89,21,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (90,21,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UNIDAD-ALMACENAMIENTO-HP-SAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (91,22,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (92,22,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (93,22,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (94,22,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (95,22,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-ES-HP-SAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (96,23,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (97,23,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (98,23,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (99,23,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (100,23,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-FC-HP-SAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (101,24,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (102,24,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (103,24,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (104,24,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (105,24,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-SATA-HP-SAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (106,25,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (107,25,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (108,25,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (109,25,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (110,25,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UNIDAD-ALMACENAMIENTO-HP-OR-SQL*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (111,26,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (112,26,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (113,26,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (114,26,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (115,26,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-DISCO-ES-BD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (116,27,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (117,27,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (118,27,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (119,27,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (120,27,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-DISCO-ES-BD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (121,28,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (122,28,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (123,28,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (124,28,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (125,28,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-LINUX*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (126,29,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (127,29,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (128,29,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (129,29,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (130,29,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-DEBIAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (131,30,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (132,30,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (133,30,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (134,30,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (135,30,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-SLES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (136,31,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (137,31,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (138,31,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (139,31,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (140,31,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-CENTOS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (141,32,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (142,32,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (143,32,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (144,32,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (145,32,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-UBUNTU*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (146,33,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (147,33,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (148,33,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (149,33,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (150,33,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-OREACLE-LINUX-SERVER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (151,34,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (152,34,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (153,34,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (154,34,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (155,34,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-WINDOWS-SERVER-2008*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (156,35,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (157,35,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (158,35,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (159,35,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (160,35,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SO-WINDOWS-SERVER-2012*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (161,36,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (162,36,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (163,36,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (164,36,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (165,36,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVIDOR-VIRTUAL-RISC-SPARC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (166,37,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (167,37,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (168,37,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (170,37,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVIDOR-VIRTUAL-RISC-POWER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (171,38,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (172,38,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (173,38,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (174,38,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA SERVIDOR-VIRTUAL-RISC-ITANIUM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (175,39,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (176,39,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (177,39,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (178,39,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1PROC-VIRT-RISC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (179,40,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (180,40,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (181,40,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (182,40,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-32GB-MEM-VIRT-RISC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (183,41,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (184,41,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (185,41,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (186,41,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA SERVIDOR-VIRTUAL-X86*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (187,42,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (188,42,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (189,42,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (190,42,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1PROC-VIRT-X86*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (191,43,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (192,43,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (193,43,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (194,43,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (195,43,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1PROC-VIRT-X86*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (196,44,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (197,44,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (198,44,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (199,44,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (200,44,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA PUNTO-ACCESO-NUBE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (201,45,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ESCRITORIO-NUBE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (202,46,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA PLATAFORMA-VIRTUALIZACION-MT*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (203,47,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (204,47,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (205,47,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (206,47,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (207,47,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA PUNTO-NEUTRO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (208,48,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (209,48,2);

/*OBTIENE BLOQUE CONSTRUCCION PARA PUNTO-NEUTRO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (210,49,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (211,49,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (212,49,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (213,49,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (214,49,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-32MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (215,50,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (216,50,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (217,50,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (218,50,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (219,50,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-50MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (220,51,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (221,51,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (222,51,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (223,51,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (224,51,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-100MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (225,52,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (226,52,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (227,52,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (228,52,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (229,52,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-250MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (230,53,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (231,53,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (232,53,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (233,53,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (234,53,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-500MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (235,54,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (236,54,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (237,54,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (238,54,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (239,54,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-1GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (240,55,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (241,55,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (242,55,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (243,55,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (244,55,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-3GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (245,56,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (246,56,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (247,56,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (248,56,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (249,56,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-5GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (250,57,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (251,57,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (252,57,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (253,57,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (254,57,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-MPLS-10GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (255,58,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (256,58,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (257,58,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (258,58,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (259,58,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-10MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (260,59,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (261,59,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (262,59,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (263,59,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (264,59,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-32MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (265,60,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (266,60,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (267,60,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (268,60,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (269,60,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-50MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (270,61,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (271,61,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (272,61,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (273,61,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (274,61,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-100MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (275,62,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (276,62,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (277,62,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (278,62,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (279,62,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-250MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (280,63,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (281,63,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (282,63,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (283,63,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (284,63,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-500MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (285,64,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (286,64,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (287,64,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (288,64,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (289,64,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-1GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (290,65,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (291,65,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (292,65,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (293,65,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (294,65,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-3GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (295,66,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (296,66,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (297,66,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (298,66,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (299,66,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-5GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (300,67,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (301,67,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (302,67,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (303,67,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (304,67,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-MPLS-10GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (305,68,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (306,68,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (307,68,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (308,68,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (309,68,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-10MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (310,69,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (311,69,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (312,69,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (313,69,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (314,69,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-32MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (315,70,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (316,70,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (317,70,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (318,70,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (319,70,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-50MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (320,71,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (321,71,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (322,71,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (323,71,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (324,71,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-100MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (325,72,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (326,72,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (327,72,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (328,72,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (329,72,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-250MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (330,73,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (331,73,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (332,73,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (333,73,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (334,73,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-500MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (335,74,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (336,74,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (337,74,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (338,74,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (339,74,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-1GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (340,75,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (341,75,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (342,75,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (343,75,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (344,75,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-3GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (345,76,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (346,76,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (347,76,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (348,76,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (349,76,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-5GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (350,77,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (351,77,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (352,77,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (353,77,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (354,77,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-L2L-10GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (355,78,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (356,78,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (357,78,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (358,78,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (359,78,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-10MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (360,79,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (361,79,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (362,79,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (363,79,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (364,79,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-32MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (365,80,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (366,80,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (367,80,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (368,80,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (369,80,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-50MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (370,81,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (371,81,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (372,81,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (373,81,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (374,81,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-100MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (375,81,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (376,82,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (377,82,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (378,82,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (379,82,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-250MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (380,83,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (381,83,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (382,83,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (383,83,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (384,83,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-500MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (385,84,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (386,84,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (387,84,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (388,84,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (389,84,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-1GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (390,85,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (391,85,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (392,85,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (393,85,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (394,85,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-3GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (395,86,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (396,86,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (397,86,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (398,86,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (399,86,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-5GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (400,87,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (401,87,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (402,87,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (403,87,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (404,87,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-L2L-10GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (405,88,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (406,88,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (407,88,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (408,88,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (409,88,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UTM-BA-100MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (410,89,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (411,89,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (412,89,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (413,89,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (414,89,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UTM-BA-10GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (415,90,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (416,90,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (417,90,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (418,90,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (419,90,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ACELERADOR-WAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (420,91,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (421,91,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (422,91,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (423,91,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (424,91,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA GESTOR-WAN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (425,92,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (426,92,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (427,92,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (428,92,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (429,92,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA BALANCEADOR-L4-L7*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (430,93,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (431,93,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (432,93,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (433,93,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (434,93,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA PLATAFORMA-NODO-EXT-NP-CHICO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (435,94,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA PLATAFORMA-NODO-EXT-NP-CHICO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (436,95,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA NODO-EXT-NP-HIBRIDA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (437,96,4);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-Híbrida*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (438,97,4);

/*OBTIENE BLOQUE CONSTRUCCION PARA PISO-BLANCO-X_MT2*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (439,98,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (440,98,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (441,98,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (442,98,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ESPACIO-RACK*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (443,99,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (444,99,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (445,99,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (446,99,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA OPEN-AM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (447,100,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (448,100,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (449,100,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (450,100,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (451,100,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA GESTOR-IDM-ORACLE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (452,101,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (453,101,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (454,101,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (455,101,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (456,101,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA NETIQ-ACCESS-GATEWAY*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (457,102,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (458,102,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (459,102,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (460,102,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (461,102,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA MICROSOFT-REPORTING-SERVICES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (462,103,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (463,103,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (464,103,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (465,103,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (466,103,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ESSBASE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (467,104,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (468,104,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (469,104,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (470,104,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (471,104,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ESSBASE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (472,104,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (473,104,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (474,104,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (475,104,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (476,104,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA HYPERION*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (477,105,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (478,105,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (479,105,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (480,105,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (481,105,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA VISUALIZACION-ANALISIS-INFORMACION*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (482,106,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (483,106,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (484,106,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (485,106,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (486,106,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-BI*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (487,107,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (488,107,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (489,107,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (490,107,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (491,107,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA MICROSOFT-ANALISIS-SERVICES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (492,108,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (493,108,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (494,108,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (495,108,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (496,108,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SAS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (497,109,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (498,109,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (499,109,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (500,109,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (501,109,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-EXALYTICS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (502,110,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (503,110,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (504,110,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (505,110,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (506,110,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA TABLEAU-SERVER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (507,111,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (508,111,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (509,111,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (510,111,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (511,111,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA TABLEAU-DESKTOP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (512,112,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (513,112,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (514,112,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (515,112,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (516,112,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA STATA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (517,113,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (518,113,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (519,113,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (520,113,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (521,113,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA IBM-DATA-STAGE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (522,115,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (523,115,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (524,115,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (525,115,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (526,115,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA MICROSOFT-INTEGRATION SERVICES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (527,116,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (528,116,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (529,116,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (530,116,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-WAREHOUSE-BUILDER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (531,117,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (532,117,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (533,117,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (534,117,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (535,117,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA INTEGRACION-TRANSFORMACION-INFO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (536,118,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (537,118,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (538,118,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (539,118,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (540,118,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA REDBRICK*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (541,119,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (542,119,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (543,119,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (544,119,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (545,119,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA STATA-TRANSFER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (546,120,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (547,120,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (548,120,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (549,120,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (550,120,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-GOLDEN-GATE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (551,121,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (552,121,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (553,121,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (554,121,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (555,121,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-DATA-QUALITY*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (556,122,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (557,122,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (558,122,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (559,122,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (560,122,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA BD-ORACLE-STANDALONE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (561,123,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (562,123,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (563,123,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (564,123,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (565,123,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA BD-ORACLE-RAC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (566,124,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (567,124,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (568,124,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (569,124,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (570,124,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA BD-MICROSOFT-SQLSERVER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (571,125,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (572,125,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (573,125,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (574,125,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (575,125,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA BD-DB2*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (576,126,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (577,126,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (578,126,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (579,126,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (580,126,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SUBSCRIPCIONES-BD-OPENSOURCE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (581,127,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (582,127,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (583,127,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (584,127,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (585,127,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-EXADATA-STORAGE-EXPANSION*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (586,128,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (587,128,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (588,128,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (589,128,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (590,128,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SQL-SERVER-PARALLEL-DATAWAREHOUSE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (591,129,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (592,129,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (593,129,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (594,129,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (595,129,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA OPEN-DJ*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (596,130,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (597,130,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (598,130,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (599,130,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (600,130,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA JAVA-SE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (601,135,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (602,135,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (603,135,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (604,135,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA JAVA-RTE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (605,136,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (606,136,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (607,136,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (608,136,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (609,136,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA DOT-NET-Framework*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (610,137,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (611,137,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (612,137,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (613,137,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (614,137,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA DRUPAL*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (615,138,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (616,138,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (617,138,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (618,138,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (619,138,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA LIFERAY-ENTERPRISE-7-24*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (620,139,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (621,139,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (622,139,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (623,139,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (624,139,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA LIFERAY-ENTERPRISE-5-8*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (625,140,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (626,140,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (627,140,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (628,140,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (629,140,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ADOBE-COLDFUSION*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (630,141,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (631,141,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (632,141,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (633,141,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (634,141,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-SERVICE-BUS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (635,142,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (636,142,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (637,142,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (638,142,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (639,142,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-ALSB*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (640,143,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (641,143,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (642,143,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (643,143,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (644,143,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-ALDS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (645,144,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (646,144,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (647,144,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (648,144,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (649,144,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA REDHAT-JBOSS-FUSE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (650,145,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (651,145,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (652,145,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (653,145,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (654,145,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SOA-SUITE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (655,146,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (656,146,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (657,146,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (658,146,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (659,146,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA APACHE-KAFKA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (660,147,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (661,147,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (662,147,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (663,147,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (664,147,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-ENTERPISE-REPOSITORY*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (665,148,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (666,148,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (667,148,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (668,148,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (669,148,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-SERVICE-REGISTRY*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (670,149,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (671,149,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (672,149,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (673,149,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (674,149,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA REDHAT-JBOSS-SOA-ENTERPISE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (675,150,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (676,150,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (677,150,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (678,150,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (679,150,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA WEBLOGIC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (680,151,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (681,151,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (682,151,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (683,151,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (684,151,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA TUXEDO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (685,152,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (686,152,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (687,152,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (688,152,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (689,152,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA GLASSFISH*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (690,153,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (691,153,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (692,153,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (693,153,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (694,153,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA REDHAT-JBOSS-ENTERPISE-APP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (695,154,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (696,154,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (697,154,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (698,154,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (699,154,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA APACHE-TOMCAT*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (700,155,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (701,155,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (702,155,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (703,155,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (704,155,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA APACHE-HTTPD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (705,156,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (706,156,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (707,156,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (708,156,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (709,156,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-EXALOGIC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (710,157,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (711,157,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (712,157,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (713,157,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (714,157,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-BPM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (715,158,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (716,158,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (717,158,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (718,158,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (719,158,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA REDHAT-JBOSS-BPM-SUITE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (720,159,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (721,159,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (722,159,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (723,159,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (724,159,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA MOTOR-REGLAS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (725,160,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (726,160,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (727,160,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (728,160,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (729,160,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-CORREO-ELECTRONICO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (730,161,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (731,161,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (732,161,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (733,161,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (734,161,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA LYNC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (735,162,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (736,162,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (737,162,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (738,162,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (739,162,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA GESTOR-PPM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (740,163,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (741,163,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (742,163,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (743,163,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (744,163,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA USUARIO-ACCESO-NP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (745,164,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (746,164,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (747,164,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (748,164,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (749,164,6);	

/*OBTIENE BLOQUE CONSTRUCCION PARA USUARIO-ACCESO-NP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (750,164,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (751,164,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (752,164,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (753,164,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (754,164,6);

/**FIXME AGREGAR AUTO INCREMENTABLE*/
/*OBTIENE BLOQUE CONSTRUCCION PARA UNIDAD-RESPALDO-MF*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (755,8,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (756,8,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (757,8,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (758,8,6);

/**FIXME AGREGAR AUTO INCREMENTABLE*/
/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-1TB-DISCO-ES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (759,17,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (760,17,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (761,17,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (762,17,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (763,17,6);

/**FIXME AGREGAR AUTO INCREMENTABLE*/
/*OBTIENE BLOQUE CONSTRUCCION PARA ORACLE-ODI*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (764,114,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (765,114,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (766,114,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (767,114,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (768,114,6);

/**FIXME AGREGAR AUTO INCREMENTABLE*/
/*OBTIENE BLOQUE CONSTRUCCION PARA MICROSOFT-INTEGRATION SERVICES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (769,116,1);


/*OBTIENE BLOQUE CONSTRUCCION PARA NETIQ-IDENTITY-PROVIDER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (770,131,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (771,131,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (772,131,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (773,131,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (774,131,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA PLATAFORMA-LDAP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (775,132,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (776,132,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (777,132,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (778,132,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (779,132,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA TEAM-FOUNDATION-SERVER*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (780,133,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (781,133,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (782,133,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (783,133,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA JAVA-SDK*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (784,134,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (785,134,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (786,134,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (787,134,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (788,134,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA JAVA-SE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (789,135,1);

/*OBTIENE BLOQUE CONSTRUCCION PARA SHAREPOINT*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (790,165,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (791,165,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (792,165,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (793,165,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (794,165,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SOFTWARE-MP-ADMIN-ARCHIVOS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (795,166,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (796,166,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (797,166,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (798,166,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (799,166,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA FIREWALL*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (800,167,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (801,167,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (802,167,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (803,167,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (804,167,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA IPS-IPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (805,168,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (806,168,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (807,168,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (808,168,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (809,168,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ANTI-DDOS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (810,169,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (811,169,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (812,169,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (813,169,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (814,169,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA RED-VPN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (815,170,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (816,170,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (817,170,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (818,170,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (819,170,6);


/*OBTIENE BLOQUE CONSTRUCCION PARA UTM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (820,171,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (821,171,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (822,171,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (823,171,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (824,171,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA FILTRADO-CONTENIDO-WEB*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (825,172,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (826,172,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (827,172,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (828,172,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (829,172,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ANTISPAM*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (830,173,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (831,173,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (832,173,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (833,173,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (834,173,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ANTIMALWARE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (835,174,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (836,174,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (837,174,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (838,174,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (839,174,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA FIREWALL-WAF*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (840,175,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (841,175,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (842,175,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (843,175,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (844,175,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA FIREWALL-DATOS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (845,176,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (846,176,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (847,176,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (848,176,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (849,176,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA NODO-RED-UTP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (850,177,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (851,177,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (852,177,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (853,177,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (854,177,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA NODO-RED-FO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (855,178,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (856,178,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (857,178,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (858,178,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (859,178,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA CABLEADO-FO-X-MT-INMUEBLES*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (860,179,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (861,179,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (862,179,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (863,179,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (864,179,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SWITCH-10G-CORE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (865,180,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (866,180,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (867,180,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (868,180,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (869,180,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SWITCH-1G-DISTRIBUCIÓN*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (870,181,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (871,181,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (872,181,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (873,181,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (874,181,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA CABLEADO-LAN-NODO-ACCESO-NUBE*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (875,182,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (876,182,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (877,182,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (878,182,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (879,182,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA UTM-NIBA-100MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (880,183,5);

/*OBTIENE BLOQUE CONSTRUCCION PARA UTM-NIBA-1GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (881,184,5);

/*OBTIENE BLOQUE CONSTRUCCION PARA UTM-NIBA-10GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (882,185,5);

/*INCREMENTO-AB-NH-10MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (883,186,4);

/*INCREMENTO-AB-NH-32MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (884,187,4);

/*INCREMENTO-AB-NH-50MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (885,188,4);

/*OBTIENE BLOQUE CONSTRUCCION INCREMENTO-AB-NH-100MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (886,189,4);

/*INCREMENTO-AB-NH-250MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (887,190,4);

/*INCREMENTO-AB-NH-500MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (888,191,4);

/*INCREMENTO-AB-NH-1GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (889,192,4);

/*INCREMENTO-AB-NH-3GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (890,193,4);

/*INCREMENTO-AB-NH-5GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (891,194,4);

/*INCREMENTO-AB-NH-10GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (892,195,4);

/*OBTIENE BLOQUE CONSTRUCCION PARA DISPOSITIVO-MF-SEG-PER-100MBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (893,196,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (894,196,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (895,196,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (896,196,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (897,196,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA DISPOSITIVO-MF-SEG-PER-1GBPS*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (898,197,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (899,197,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (900,197,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (901,197,5);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (902,197,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-2MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (903,198,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (904,198,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (905,198,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-10MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (906,199,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (907,199,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (908,199,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-32MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (909,200,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (910,200,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (911,200,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-50MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (912,201,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (913,201,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (914,201,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-100MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (915,202,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (916,202,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (917,202,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-250MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (918,203,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (919,203,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (920,203,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-500MBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (921,204,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (922,204,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (923,204,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-1GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (924,205,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (925,205,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (926,205,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-3GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (927,206,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (928,206,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (929,206,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-5GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (930,207,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (931,207,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (932,207,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA ENLACE-INTERNET-10GBPS-REDUN-AA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (933,208,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (934,208,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (935,208,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-10MBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (936,209,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (937,209,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (938,209,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-32MBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (939,210,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (940,210,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (941,210,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-50MBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (942,211,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (943,211,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (944,211,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-100MBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (945,212,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (946,212,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (947,212,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-250MBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (948,213,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (949,213,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (950,213,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-500MBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (951,214,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (952,214,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (953,214,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-1GBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (954,215,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (955,215,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (956,215,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-3GBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (957,216,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (958,216,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (959,216,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-5GBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (960,217,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (961,217,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (962,217,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-AB-INTERNET-10GBPS-RAA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (963,218,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (964,218,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (965,218,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA SISTEMA-ALMACENAMIENO-12TB-RAID5*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (966,219,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (967,219,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (968,219,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA INCREMENTO-ALM-RAID5-1TB*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (969,220,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (970,220,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (971,220,3);

/*OBTIENE BLOQUE CONSTRUCCION PARA SOLUCION-WCAG*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (972,221,1);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (973,221,2);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (974,221,3);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (975,221,6);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-RECOM-ALINEACIÓN-TECNO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (976,222,7);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-ESTABLECER-ARQ*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (977,223,7);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-INTEGRACIÓN-TECNO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (978,224,7);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-GOBIERNO*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (979,225,8);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-ARQUITECTURA-TECNOLÓGICA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (980,226,7);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-PLATAFORMA-CALIDAD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (981,227,7);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-INTEGRIDAD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (982,228,9);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-CALIDAD-SEGURIDAD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (983,229,11);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-OPERACIÓN-SEGURIDAD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (984,230,11);

/*OBTIENE BLOQUE CONSTRUCCION PARA SERVICIO-CONTINUIDAD-OPERATIVA*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (985,231,10);

/*OBTIENE BLOQUE CONSTRUCCION PARA MIGRACIÓN-CD*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (986,232,10);

/*OBTIENE BLOQUE CONSTRUCCION PARA PORCENTAJE-BCC*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (987,233,7);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (988,233,8);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (989,233,9);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (990,233,10);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (991,233,11);

/*OBTIENE BLOQUE CONSTRUCCION PARA PORCENTAJE-DRP*/
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (992,234,7);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (993,234,8);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (994,234,9);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (995,234,10);
INSERT INTO KIO_MODALIDAD_BLOQUE VALUES (996,234,11);































