INSERT INTO KIO_CATALOGOREQUERIMIENTOS VALUES (1,'Calidad');
INSERT INTO KIO_CATALOGOREQUERIMIENTOS VALUES (2,'Crecimiento Nueva Infraestructura');
INSERT INTO KIO_CATALOGOREQUERIMIENTOS VALUES (3,'Proyectos');
INSERT INTO KIO_CATALOGOREQUERIMIENTOS VALUES (4,'Otros');